server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url: postgres://pzowtpinbwjlhy:b02d5bc9e8206340fa7b9a089c0dc8a9dae86c3c65f1d7e0a6bab0967014b6e3@ec2-54-236-137-173.compute-1.amazonaws.com:5432/d7vb28447mnac2
    #username: postgres
    username: pzowtpinbwjlhy
    #password: 123456
    password: b02d5bc9e8206340fa7b9a089c0dc8a9dae86c3c65f1d7e0a6bab0967014b6e3
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander