server:
  port: 8080
  servlet:
    context-path: /bootcamp
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://pzowtpinbwjlhy:b02d5bc9e8206340fa7b9a089c0dc8a9dae86c3c65f1d7e0a6bab0967014b6e3@ec2-54-236-137-173.compute-1.amazonaws.com:5432/d7vb28447mnac2
    username: pzowtpinbwjlhy
    password: b02d5bc9e8206340fa7b9a089c0dc8a9dae86c3c65f1d7e0a6bab0967014b6e3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
application:
  description: Projeto Criado para DIO Wesley